server: hub-cloud.browserstack.com
user: BROWSERSTACK_USERNAME
key: BROWSERSTACK_ACCESS_KEY

common_caps:
  build: capybara-browserstack
  browserstack.debug: true
  browserstack.local: true
  browserstack.localIdentifier: test
browser_caps:
- browser: chrome
- browser: safari
